# Generated by Django 2.0.7 on 2018-08-24 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('rg', models.IntegerField(blank=True, null=True, unique=True)),
                ('cpf', models.IntegerField(blank=True, null=True, unique=True)),
                ('ctps', models.IntegerField(blank=True, null=True, unique=True)),
                ('matricula', models.IntegerField(blank=True, null=True, unique=True)),
                ('dataNascimento', models.DateField(blank=True, null=True)),
                ('dataAdmissao', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, max_length=500)),
                ('acesso', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('funcao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funcionario.Funcao')),
            ],
        ),
    ]
